# Generated by Django 5.1.15 on 2026-09-23 21:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='订单编号')),
                ('receiver', models.CharField(max_length=64, verbose_name='收货点')),
                ('address', models.CharField(blank=True, max_length=128, verbose_name='收货地址')),
                ('item_count', models.PositiveIntegerField(default=1, verbose_name='件数')),
                ('status', models.CharField(choices=[('pending', '待分拣'), ('picking', '分拣中'), ('picked', '已拣完'), ('shipped', '已发运')], default='pending', max_length=16, verbose_name='状态')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='车辆编号')),
                ('name', models.CharField(max_length=64, verbose_name='车辆名称')),
                ('driver_alias', models.CharField(blank=True, max_length=32, verbose_name='司机化名')),
                ('capacity', models.PositiveIntegerField(default=200, verbose_name='额定载件数')),
                ('status', models.CharField(choices=[('idle', '待命'), ('loading', '装车中'), ('delivering', '配送中'), ('maintenance', '维保')], default='idle', max_length=16, verbose_name='状态')),
            ],
            options={
                'verbose_name': '配送车',
                'verbose_name_plural': '配送车',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Wave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='波次编号')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='波次名称')),
                ('zone', models.CharField(blank=True, max_length=8, verbose_name='作业库区')),
                ('status', models.CharField(choices=[('planned', '已排定'), ('picking', '分拣中'), ('done', '已完成'), ('paused', '暂停')], default='planned', max_length=16, verbose_name='状态')),
                ('planned_start', models.DateTimeField(blank=True, null=True, verbose_name='计划开始')),
                ('planned_end', models.DateTimeField(blank=True, null=True, verbose_name='计划结束')),
            ],
            options={
                'verbose_name': '分拣波次',
                'verbose_name_plural': '分拣波次',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='路线编号')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='路线名称')),
                ('stops', models.PositiveIntegerField(default=0, verbose_name='站点数')),
                ('status', models.CharField(choices=[('planned', '待发车'), ('running', '配送中'), ('done', '已送达')], default='planned', max_length=16, verbose_name='状态')),
                ('depart_at', models.DateTimeField(blank=True, null=True, verbose_name='发车时间')),
                ('orders', models.ManyToManyField(blank=True, related_name='routes', to='board.order', verbose_name='配送订单')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='board.vehicle', verbose_name='配送车')),
            ],
            options={
                'verbose_name': '配送路线',
                'verbose_name_plural': '配送路线',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PickTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='任务编号')),
                ('location', models.CharField(max_length=32, verbose_name='库位')),
                ('picker_alias', models.CharField(blank=True, max_length=32, verbose_name='拣货员化名')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='拣货件数')),
                ('status', models.CharField(choices=[('todo', '待拣'), ('doing', '拣货中'), ('done', '已完成')], default='todo', max_length=16, verbose_name='状态')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='board.order', verbose_name='关联订单')),
                ('wave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='board.wave', verbose_name='所属波次')),
            ],
            options={
                'verbose_name': '拣货任务',
                'verbose_name_plural': '拣货任务',
                'ordering': ['location'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='wave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='board.wave', verbose_name='所属波次'),
        ),
    ]
